let date = new Date()

document.write(date)
document.write('<br>')
document.write(date.getDate())
document.write('<br>')
document.write(date.getDay())
document.write('<br>')
document.write(date.getFullYear())
document.write('<br>')
document.write(date.getTime())
document.write('<br>')
document.write(date)
document.write('<br>')